services:
  n8n:
    ports:
      - '5678:5678'
    environment:
      VUE_APP_URL_BASE_API: https://n8n.${SERVER_DOMAIN:-example.com}/
      WEBHOOK_URL: https://n8n.${SERVER_DOMAIN:-example.com}
      N8N_PROTOCOL: https
      N8N_HOST: n8n.${SERVER_DOMAIN:-example.com}
      N8N_PORT: 5678
      NODE_ENV: production
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - "traefik.http.routers.n8n.rule=Host(`n8n.${SERVER_DOMAIN:-example.com}`)"
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.tls.certresolver=${TRAEFIK_TLS_CERTRESOLVER:-myresolver}
    networks:
      - traefik-network

  n8n_postgres:
    labels:
      - traefik.enable=true
      - "traefik.tcp.routers.n8n_postgres.rule=HostSNI(`*`)"
      - traefik.tcp.routers.n8n_postgres.entryPoints=postgres
      - traefik.tcp.routers.n8n_postgres.service=service_db
      - traefik.tcp.services.service_db.loadbalancer.server.port=5432
    networks:
      - traefik-network

  n8n_pgweb:
    ports:
      - '127.0.0.1:8081:8081'

networks:
  traefik-network:
    name: traefik-network
    external: true
    # driver: bridge
